#!/bin/bash

#Simple Hello World using script
echo "Hello World"

#basic arthmatic calculation 

#define an variable

num1=4
num2=7

#calculation done in echo line
echo "This is Sum of $num1 and $num2 = $((num1+num2))"

#calculation execution in separate block of code

num_result=$((num1+num2))
echo "calcultion done by separate block result is @ $num_result"

#define a constant number
declare -r const_number=221
echo "constant number is $const_number"

#prefix / postfix -> increment / decrement

echo "post-increment -> $((num1++))"
echo "post-decrement -> $((num1--))"
echo "pre-increment -> $((++num1))"
echo "pre-decrement -> $((--num1))"

#access floating point values 
numfloat=4.11
num2float=5.62

#in this execution shell scripting use python commands
result_float=$(python -c "print $numfloat+$num2float")
echo "python -> execution $result_float",#0000FF



